### ISSUE TITLE
no tail recursion?

### ISSUE THREAD

**Issue by rowet** [leftmike/foment#11]
This segfaults after 15 minutes. I'd have expected tail recursion and a runtime under 20 seconds. I assume none of this is news to you, but just in case it's helpful:

    (import (foment base))
    
    (define (sumseries)
      (let loop ((i 1) (sum 0))
        (if (> i 100000000) sum
          (loop (+ i 1) (+ sum i)))))
    
    (display (sumseries))
    (newline)

**Comment by leftmike** [comment]
Actually it is a garbage collector issue with a larger object than I expected. I am working on a fix.

**Comment by leftmike** [comment]
Which OS are you running?

**Comment by rowet** [comment]
This was linux: Fedora 24.

**Comment by leftmike** [comment]
What is the output from running: foment -p "(features)" -p "(config)"

**Comment by rowet** [comment]
x30:/var/tmp/foment/unix/release$ ./foment -p "(features)" -p "(config)"
Foment Scheme 0.4
((partial-per-full . 4) (trigger-objects . 16384) (trigger-bytes . 393216) (maximum-generational-baby . 65536) (maximum-adults-size . 4294967296) (maximum-kids-size . 0) (maximum-babies-size . 0) (maximum-stack-size . 33554432) (check-heap . #f) (collector . mark-sweep) (random-seed . 1483316019) (verbose . #f) (library-extensions "sld" "scm") (library-path "."))
(guardians little-endian linux x86-64 foment-0.4 foment threads ratios full-unicode ieee-float exact-complex exact-closed r7rs lp64 unix)

**Comment by leftmike** [comment]
Should be working now, though still slow (150 seconds). I am working on improving performance. Please close if it is fixed for you.

**Comment by leftmike** [comment]
On my machine, the time goes from 50 seconds with 28 bit fixnums to 12 seconds with 60 bit fixnums.
