### ISSUE TITLE
Cannot pipe from foment on OS X or Linux

### ISSUE THREAD

**Issue by rjungemann** [leftmike/foment#12]
I have a file, `test.scm`, which only contains:

```scheme
(display "Hello, world!")
```

If I run `foment` on its own, I get an error, as expected:

```
$ foment test.scm
#<exception: #x10b2fbd18 syntax-violation program "program: identifier(s) used but never defined" irritants: ((display) "test.scm")>
```

However, if I try and pipe from `foment` in any way, no output is shown, using `cat`, `tee` or other methods.

```
$ foment test.scm | cat
# Nothing...
```

Is this intended behavior? Is there a workaround for this?

**Comment by BernardTatin** [comment]
I have the same on Linux. If I do : 

```
foment test.scm > log
```

`log` is empty.

**Comment by leftmike** [comment]
Should be fixed now. Standard output and error were not being flushed when foment exited due to an exception. Please close once you verify this works for you.
