### ISSUE TITLE
Support dumb terminals

### ISSUE THREAD

**Issue by wasamasa** [leftmike/foment#15]
Just because you're connected to a terminal doesn't mean that sending ANSI escape codes (as done in `SetupConsole`) is OK.  Typically setting `TERM` to `dumb` (alternatively, unsetting it) is used to signal that the terminal doesn't support them at all.  In this situation the line reading function could get away with just using `fgets` or alike to get user input.

**Comment by wasamasa** [comment]
Hm, while this keeps the application happy, doing things this way stops echoing user input.  Running foment from something like `M-x scheme` in Emacs fails because it uses a pty, yet doesn't ever receive the prompt.

**Comment by leftmike** [comment]
Better fix for this issue; I tested using a shell under emacs.

**Comment by wasamasa** [comment]
Thanks again!
