### ISSUE TITLE
Standard error port is buffered

### ISSUE THREAD

**Issue by wasamasa** [leftmike/foment#16]
The default behavior in C and all other Scheme implementations I've seen is that standard error is unbuffered while standard input and output are buffered.  In Foment however standard error is unbuffered which leads to side effects such as debug messages only showing up after program exit (because by then the buffer is flushed).  If there's no objection to changing this behavior, I'd be happy handing in a PR.

**Comment by leftmike** [comment]
Yes, please submit a pull request.
