### ISSUE TITLE
Importing SRFI-1 fails

### ISSUE THREAD

**Issue by wasamasa** [leftmike/foment#19]
```
{2263016} =] (import (srfi 1))
#<exception: #x7f8ddd7b7fb0 syntax-violation import "import: library not found" irritants: ((srfi 1) (import (srfi 1)))>
{57400} =] filter
#<exception: #x7ff684ae29b0 assertion-violation variable is undefined irritants: (#<global: #x7ff684ae2890 filter interaction>)>
```

I initially thought SRFI-1 isn't provided at all, but then found it mentioned in the README and sources.  Perhaps something went wrong during the build or an export form fails?

edit: `(import (srfi 60))` works, when comparing both in `base.scm` the difference is that the former uses a `(define-library (scheme list) (aka (srfi 1)) ...)` whereas the latter uses `(define-library (srfi 60) ...)`.  This suggests that the `aka` form doesn't work.

**Comment by leftmike** [comment]
aka was broken for builtin libraries; the commit fixes it.
