### ISSUE TITLE
Batch mode

### ISSUE THREAD

**Issue by jasonmacduffie** [leftmike/foment#21]
Foment has an explicit REPL mode, but I would like an explicit "batch mode" which deactivates the repl even if reading from standard input. That way scripts can be piped into Foment.

**Comment by leftmike** [comment]
I added batch mode: -b or --batch as a command line option turns it on; when in batch mode, foment will treat standard input as a program.

`foment program.scm` and `foment --batch < program.scm` should behave identically.

Please let me know if this is what you wanted -- and if not, how I can fix it.

**Comment by jasonmacduffie** [comment]
Thank you! It works perfectly.
