### ISSUE TITLE
Global library path

### ISSUE THREAD

**Issue by jasonmacduffie** [leftmike/foment#22]
Should foment have a global library path? For example, if I say (import (srfi 28)) I would like foment to search "/usr/local/share/foment/srfi", or something similar to that. I can specify with -I but I think there should be a default.

I saw in src/foment.hpp a reference to "$(HOME)/.local/foment/lib", is that referring to this?

**Comment by leftmike** [comment]
The current behavior is documented in [UsingLibraries](https://github.com/leftmike/foment/wiki/UsingLibraries). The reference you saw in src/foment.hpp is to a future idea to possibly be implemented.

You can use the environment variable FOMENT_LIBPATH to add more directories to the library path. This is the same as Guile's [GUILE_LOAD_PATH](https://www.gnu.org/software/guile/manual/html_node/Environment-Variables.html#Environment-Variables).

What additional support for library paths would you like to have? Here are a few possible ideas.
- Something relative to the users home directory:
Windows: $(APPDATA)\Foment\Libraries
Unix: $(HOME)/.local/foment/lib
- A global directory: /usr/local/share/foment (or /usr/share/foment). This is what Guile does: [Load Paths](https://www.gnu.org/software/guile/manual/html_node/Load-Paths.html) and [Build Config](https://www.gnu.org/software/guile/manual/html_node/Build-Config.html#Build-Config).
- ???

**Comment by jasonmacduffie** [comment]
Thank you for the link; $FOMENT_LIBPATH actually covers what I need very well but I missed the wiki page. I was imagining something like your bullets (1) or (2), but I think the environment variable solution is good too.

Since foment is shipped as a single binary, I think option (1) makes more sense.
