### ISSUE TITLE
Repeatedly hitting enter after sending input to the REPL crashes Foment

### ISSUE THREAD

**Issue by jpellegrini** [leftmike/foment#29]
If I do send some simple input, and hit enter again without waiting for Foment's output, it crashes:

```
Foment Scheme 0.4 (debug)
{2235808} =] 1
1
{11984} =] 
assert: ret != 0 (2207)../src/io.cpp
```

**Comment by jpellegrini** [comment]
In `io.cpp`, `ConGetInfo`  calls `ConGetCursor`, which does this:

 ```
     strcpy(buf, "\x1B[6n");    
     write(1, buf, strlen(buf));
     ret = read(0, buf, sizeof(buf));
     if (ret < 6)   
         return(0);
```

And it returns zero here, so the problem is that `read` returned less than six. Then, back to `ConGetInfo`, the assertion `FAssert(ret != 0)` fails.

**Comment by leftmike** [comment]
I put in a type ahead support to buffer keyboard input that make come before a response for a terminal command. Please let me know if this doesn't work.
