### ISSUE TITLE
SRFI-125: eqv? predicate does not work as expected

### ISSUE THREAD

**Issue by okuoku** [leftmike/foment#35]
SRFI-125 requests `make-hash-table` should support `eqv?` for a predicate. But in Foment, `(make-hash-table eqv?)` seems instantiated as eq-hashtable.

https://srfi.schemers.org/srfi-125/srfi-125.html#Constructors

> The implementation must provide hash functions appropriate for 
> use with the predicates `eq?`, `eqv?`, `equal?`, `string=?`, and `string-ci=?`,
> and may extend this list. 

```scheme
Foment Scheme 0.4 (debug)
{2601992} =] (import (srfi 125))
{1841344} =] (define ht (make-hash-table eqv?))
{15992} =] (hash-table-set! ht 0.0 'zero)
{14600} =] (hash-table-ref ht 0.0)
#<exception: #x7f783302b6e0 assertion-violation hash-table-ref "hash-table-ref: key not found and no failure specified" irritants: (0.0)>
```

In Foment, `(eqv? 0.0 0.0) => #t` 

tested: https://github.com/leftmike/foment/commit/ebcf4cab52e244992356167a97ab27d0191ab190

**Comment by leftmike** [comment]
It should work correctly now; please let me know if it doesn't.

**Comment by okuoku** [comment]
Great, confirmed it works. Thanks.
