### ISSUE TITLE
Wiki: SRFI Support  --  wrong information

### ISSUE THREAD

**Issue by jpellegrini** [leftmike/foment#38]
Hello!

In the SRFI upport page in the wiki, the listing of SRFI 176 says it can be used with `(import scheme vector))`:

```
[SRFI 176: Version flag](https://srfi.schemers.org/srfi-176/srfi-176.html) is fully supported. (import (scheme vector)) or (import (srfi 176)) to use it.
```

**Comment by leftmike** [comment]
Is it that (import (scheme vector)) does not work? I just verified that both names work.

Or is it that it should not be available via (scheme vector) since it isn't standardized yet? If that is the case, I am happy to remove the (scheme vector) name.

**Comment by jpellegrini** [comment]
No, it's actually the wrong SRFI.  176 is command-line :grin:
